"""test

Revision ID: 72fbc79e28aa
Revises: fd4c340b9d72
Create Date: 2020-09-25 16:13:39.045550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72fbc79e28aa'
down_revision = 'fd4c340b9d72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'about_men')
    # ### end Alembic commands ###
    # pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_men', sa.VARCHAR(length=140), nullable=True))
    # ### end Alembic commands ###
